### ISSUE TITLE
Rename Options to Something Else?

### ISSUE THREAD

**Issue by joeosburn-desiringgod** [desiringgod/components-rails#12]
There has been some discussion on renaming the options parameter here: https://github.com/desiringgod/components-rails/blob/master/lib/components/rails/component.rb#L22 to something else.

@scottcorgan and anyone else, feel free to link other conversations related to that here.

A couple of potential options are `attributes` or `properties`.

I personally like `attributes`, because this is still Ruby, and `attributes` is a commonly used Ruby/Rails word, but lacks the drawbacks of the word `options`.

If you want to weigh in with conversation, feel free to do so. If you want to weigh in with a single word that's your vote, feel free to do that, and possibly we can form some consensus and close out this Issue quickly.

**Comment by shanebo** [comment]
`attributes`

**Comment by shanebo** [comment]
`properties`

**Comment by shanebo** [comment]
`attributes` for required
`options` for optional attributes

**Comment by scottcorgan** [comment]
I think they'll all just be considered in one name, but the goal is to throw an error for any we forgot

**Comment by scottcorgan** [comment]
@shanebo @hchasey note that there are class properties that we set to indicate if they're required or optional. And if they're optional, we give a default value.

See https://github.com/desiringgod/components-rails/pull/10#issuecomment-324106930
