### ISSUE TITLE
Fix/Improve Caching

### ISSUE THREAD

**Issue by benhutton** [desiringgod/components-rails#15]
- [ ] Move `instrument_payload` data into the correct place
 - [ ] Add in template digesting

**Comment by benhutton** [comment]
https://github.com/rails/rails/blob/v5.1.3/actionview/lib/action_view/digestor.rb

**Comment by joeosburn-desiringgod** [comment]
@benhutton Can we expand on this at all? I do recall this conversation, but now, without more details, I can't recall the specifics of this.

**Comment by benhutton** [comment]
@joeosburn-desiringgod sure!

1. You originally misunderstood what `instrument_payload` was doing. It is literally about instrumenting, not actually doing anything to the cache key....
2. Thus, what's most important is that the cache key of a component include the component name. We've started manually including the component name in a few cache keys where it would be too simple otherwise.
3. The precipitating problem was when a series toggle component started rendering as something else, because the cache key was just the series.
4. In addition to those fixes, it would be nice to add in template digesting. That is, the cache key should include some sort of hash of the view templates that the component references. That way view changes bust the cache automatically, like they do in the rest of `ActionView`
